version: "2"

services:
    hommod_flask:
        build:
            context: .
            dockerfile: Dockerfile-flask
        ports:
            - "7001:7001"
        links:
            - "rabbitmq:amq"
            - "redis:redis"
        volumes:
            - "/srv/hommod:/data"
    hommod_celery:
        build:
            context: .
            dockerfile: Dockerfile-celery
        links:
            - "redis:redis"
            - "rabbitmq:amq"
            - "hommod_flask"
            - "hommod_databanks"
        volumes:
            - "/srv/hommod:/data"
            - "/srv/backup/cmbi4/data:/mnt/cmbi4"
    hommod_databanks:
        build:
            context: .
            dockerfile: Dockerfile-databanks
        volumes:
            - "/srv/hommod:/data"
    redis:
        image: redis
    rabbitmq:
        image: rabbitmq
